spring:
  application:
    name: edge-service

server:
  port: 8083
   
eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8082/eureka}
  instance:
    preferIpAddress: true
